import { Router } from "express";

import {
  createCasualtyTriageAssessment,
  createCasualtyTransportRecord,
  createCasualty,
  deleteCasualtyRecord,
  getCasualties,
  getCasualtyCaseLinks,
  getCasualtyById,
  getNextCasualtyIdSequence,
  getCasualtyStatusHistory,
  getCasualtyTriageHistory,
  getCasualtyTransportHistory,
  getCasualtyTreatmentHistory,
  getCasualtyVerificationActionLogs,
  getCasualtyVerificationHistory,
  matchCasualtyCaseRecords,
  unmatchCasualtyCaseRecord,
  updateCasualty,
  updateCasualtyVerification,
} from "../controllers/casualty.controller.js";
import { requireAuth, requireRole } from "../middleware/auth.js";

export const casualtyRouter = Router();

casualtyRouter.get("/", requireAuth, getCasualties);
casualtyRouter.get(
  "/next-id-sequence",
  requireAuth,
  getNextCasualtyIdSequence,
);
casualtyRouter.get(
  "/verification-action-logs",
  requireAuth,
  requireRole([
    "super_admin",
    "admin",
    "administrator",
  ]),
  getCasualtyVerificationActionLogs,
);
casualtyRouter.get(
  "/case-links",
  requireAuth,
  requireRole([
    "super_admin",
    "admin",
    "administrator",
  ]),
  getCasualtyCaseLinks,
);
casualtyRouter.post(
  "/case-links",
  requireAuth,
  requireRole([
    "super_admin",
    "admin",
    "administrator",
  ]),
  matchCasualtyCaseRecords,
);
casualtyRouter.delete(
  "/:id/case-link",
  requireAuth,
  requireRole([
    "super_admin",
    "admin",
    "administrator",
  ]),
  unmatchCasualtyCaseRecord,
);
casualtyRouter.get(
  "/:id/status-history",
  requireAuth,
  getCasualtyStatusHistory,
);
casualtyRouter.get(
  "/:id/verification-history",
  requireAuth,
  getCasualtyVerificationHistory,
);
casualtyRouter.patch(
  "/:id/verification",
  requireAuth,
  requireRole([
    "super_admin",
    "admin",
    "administrator",
  ]),
  updateCasualtyVerification,
);
casualtyRouter.get(
  "/:id/triage-history",
  requireAuth,
  getCasualtyTriageHistory,
);
casualtyRouter.post(
  "/:id/triage-history",
  requireAuth,
  requireRole([
    "super_admin",
    "administrator",
    "responder",
    "encoder",
    "medical_personnel",
  ]),
  createCasualtyTriageAssessment,
);
casualtyRouter.get(
  "/:id/transport-history",
  requireAuth,
  getCasualtyTransportHistory,
);
casualtyRouter.get(
  "/:id/treatment-history",
  requireAuth,
  getCasualtyTreatmentHistory,
);
casualtyRouter.post(
  "/:id/transport-history",
  requireAuth,
  requireRole([
    "super_admin",
    "administrator",
    "responder",
    "encoder",
    "medical_personnel",
  ]),
  createCasualtyTransportRecord,
);
casualtyRouter.get("/:id", requireAuth, getCasualtyById);
casualtyRouter.post(
  "/",
  requireAuth,
  requireRole([
    "super_admin",
    "administrator",
    "responder",
    "encoder",
    "medical_personnel",
  ]),
  createCasualty,
);
casualtyRouter.put(
  "/:id",
  requireAuth,
  requireRole([
    "super_admin",
    "administrator",
    "responder",
    "encoder",
    "medical_personnel",
  ]),
  updateCasualty,
);
casualtyRouter.delete(
  "/:id",
  requireAuth,
  requireRole([
    "super_admin",
    "admin",
    "administrator",
  ]),
  deleteCasualtyRecord,
);
